spec:
  networking:
    name: apps-vpc
    cidrBlock: "10.0.0.0/16"
    subnets:
    - name: apps-subnet-1a-priv
      cidrBlock: "10.0.0.0/24"
      publicIpOnLaunch: false
      availabilityZone: "us-east-1a"
      tags:
        "kubernetes.io/role/internal-elb": 1
        "kubernetes.io/cluster/cluster-test": owned

    - name: apps-subnet-1b-priv
      cidrBlock: "10.0.1.0/24"
      publicIpOnLaunch: false
      availabilityZone: "us-east-1b"
      tags:
        "kubernetes.io/role/internal-elb": 1
        "kubernetes.io/cluster/cluster-test": owned

    - name: apps-subnet-1a-pub
      cidrBlock: "10.0.2.0/24"
      publicIpOnLaunch: true
      availabilityZone: "us-east-1a"
      tags:
        "kubernetes.io/role/elb": 1
        "kubernetes.io/cluster/cluster-test": owned

    - name: apps-subnet-1b-pub
      cidrBlock: "10.0.3.0/24"
      publicIpOnLaunch: true
      availabilityZone: "us-east-1b"
      tags:
        "kubernetes.io/role/elb": 1
        "kubernetes.io/cluster/cluster-test": owned

  cluster:
    name: cluster-test-new
    environment: dev
    region: us-east-1
    kubernetesVersion: "1.31"
    vpcId: apps-vpc
    subnets: ["apps-subnet-1a-pub", "apps-subnet-1b-pub"]
    securityGroups: ["sg-102930sdccc", "sg-102390c0s"]

  nodeGroups:
  - name: ng-dev-test
    scalingConfig:
      minSize: 1
      desiredSize: 1
      maxSize: 1
    instanceType: t3.medium
    imageId: "ami-0181ca43ef1eba8ed"
    nodeLabels:
      apps: pulumi-app

  helmChartsComponentes:
    components:
    - name: alb-controller
      version: "1.11.0"
      repository: "https://aws.github.io/eks-charts"
      namespace: "kube-system"
      skipCidrs: false
      setValues:
        foo: bar